### ISSUE TITLE
Tests for missing playground apps

### ISSUE THREAD

**Issue by radical** [microsoft/aspire#5210]
- [ ] Convert the test project to be built on the build machine, and then run on helix similar to workload tests.
- [ ] Test to check that the generated manifest is the same as the on disk. (see https://github.com/dotnet/aspire/pull/5208#issuecomment-2272509638) - https://github.com/dotnet/aspire/issues/4297

# Add more playground apps

- [ ] BrowserTelemetry
- [ ] DatabaseMigration
- [ ] OracleEndToEnd
- [ ] Stress
- [ ] orleans
- [ ] python
- [ ] webpubsub (test the webapp?)
- [ ] :red_circle: dapr (https://github.com/dotnet/aspire/pull/5416)
- [ ] 🔴 AspireEventHub (blocked: https://github.com/dotnet/aspire/pull/5319)
- [x] ~~🔴 Elasticsearch (blocked: https://github.com/dotnet/aspire/issues/5283)~~
- [x] 🔴 mongo (blocked: needs docker desktop - https://github.com/dotnet/aspire/issues/5274/)
- [x] AzureStorageEndToEnd (https://github.com/dotnet/aspire/pull/5316)
- [x] `CosmosEndtoEnd` - https://github.com/dotnet/aspire/pull/5244 depends on https://github.com/dotnet/aspire/pull/5218
- [x] ParameterEndToEnd (https://github.com/dotnet/aspire/pull/5252)
- [x] PostgresEndToEnd (https://github.com/dotnet/aspire/pull/5252)
- [x] ProxylessEndToEnd
- [x] Qdrant
- [x] SqlServerEndToEnd (https://github.com/dotnet/aspire/pull/5252)
- [x] TestShop
- [x] seq
- [x] `keycloak` - https://github.com/dotnet/aspire/pull/5220
- [x] milvus (https://github.com/dotnet/aspire/pull/5294)
- [x] mysql
- [x] nats
- [x] withdockerfile (https://github.com/dotnet/aspire/pull/5395)
- [x] kafka (https://github.com/dotnet/aspire/pull/5395)

## Needs custom tests

- [ ] CustomResources

## Need external resources

- [ ] :orange_circle: AzureSearchEndToEnd (`Resource could not be provisioned because Azure subscription, location, and resource group information is missing.`)
- [ ] :orange_circle: AWS (` Unable to find the "default" profile in CredentialProfileStoreChain`)
- [ ] :orange_circle: bicep (`Resource could not be provisioned because Azure subscription, location, and resource group information is missing`)
- [ ] 🟠 cdk (`Resource could not be provisioned because Azure subscription, location, and resource group information is missing`)
- [ ] 🟠  OpenAIEndToEnd (`Resource could not be provisioned because Azure subscription, location, and resource group information is missing.`
- [ ] 🟠 signalr (`Resource could not be provisioned because Azure subscription, location, and resource group information is missing`)

**Comment by radical** [comment]
cc @joperezr @sebastienros @eerhardt
