### ISSUE TITLE
Tracking issue for testing tasks blocked due to no `docker desktop` available on CI

### ISSUE THREAD

**Issue by radical** [microsoft/aspire#5325]
`Docker desktop` is not yet available on our CI. It is needed to have inter-container communication.

- [ ] EventHubs emulator - https://github.com/dotnet/aspire/issues/5371
- [ ] Testing any docker dependent tests on CI/Windows
- [x] https://github.com/microsoft/usvc/issues/164
- [ ] `RedisInsight` - https://github.com/dotnet/aspire/pull/5227#issuecomment-2293772081
- [x] `WithPgWeb` - https://github.com/dotnet/aspire/pull/5098
- [x] `Mongo` playground app - for `mongo-express` (https://github.com/dotnet/aspire/issues/5274)
- [ ] `TestShop` playground app - for `WithRedisCommander`

cc @eerhardt @sebastienros @joperezr

**Comment by Alirexaa** [comment]
@radical 
[Add WithPgWeb ](https://github.com/dotnet/aspire/pull/5098)
https://github.com/dotnet/aspire/pull/5098#issuecomment-2293762429

**Comment by davidfowl** [comment]
Yep

**Comment by radical** [comment]
Stale.
